### PR TITLE
Upgrade project to dnx451 & dnxcore50

### PR DESCRIPTION
**Pull request by piXel-m**
@mj1856 I've the need to upgrade the project to the dnx project structure and upgrade to dnxcore.
Currently I've upgraded the GeoTimeZone to dnxcore50. The Builder project based on external projects, so it just stay on dnx451.
Maybe you need setup the nuget creation. Right now this is creates the version 1.0.0.

### CODE REVIEW

**Comment by mj1856** [comment]
I'll take a look at this soon.  Thanks.

**Comment by jahto** [comment]
Hi. Now when .Net Core 1.0 has finally arrived, have you started thinking about upgrading the project. I'm going to need it in the future. But I'm also perfectly capable of forking, doing the upgrade myself and sending a pull request. When I have the time. Just immediately I don't. But after July 18, when all of my co-workers are on holiday, I'm alone at the office for two weeks, I think I could have the time. So what do you think? And thanks for the great library!

**Comment by piXel-m** [comment]
Hey,

if you've capacity to upgrading the project, it will be perfect to me, cause my project is in a time critical phase. If you needs some help, please feel free to contact me.

With kind regards from Germany,

piXel

Send with my Windows Phone.
________________________________
Von: Jouni Ahto<mailto:notifications@github.com>
Gesendet: ‎06.‎07.‎2016 18:57
An: mj1856/GeoTimeZone<mailto:GeoTimeZone@noreply.github.com>
Cc: piXel-m<mailto:git.pixel@outlook.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [mj1856/GeoTimeZone] Upgrade project to dnx451 & dnxcore50 (#20)

Hi. Now when .Net Core 1.0 has finally arrived, have you started thinking about upgrading the project. I'm going to need it in the future. But I'm also perfectly capable of forking, doing the upgrade myself and sending a pull request. When I have the time. Just immediately I don't. But after July 18, when all of my co-workers are on holiday, I'm alone at the office for two weeks, I think I could have the time. So what do you think? And thanks for the great library!

---

**Comment by jahto** [comment]
I think I've got it ready now. See my fork at https://github.com/jahto/GeoTimeZone. I chose very different approach to solve the problem. Instead of converting everything to xprojects, I just added GeoTimeZone.CORE to the solution, and use that to compile and target .NETPortable,Version=v4.0,Profile=Profile136, .NETPortable,Version=v4.5,Profile=Profile259 and netstandard1.0, which I think should cover enough platforms. Then it's just "dotnet pack" to create a nuget-package.

**Comment by mj1856** [comment]
Hi.  Sorry again for the delays on this, but version 2.0.0 now supports .NET Core.

Thanks.

**Pull request closed without merging**
